apiVersion: v1
kind: ConfigMap
data:
  {{- if .Values.deployAlertWithBlackDuck }}
  ALERT_HOSTNAME: localhost
  HUB_WEBAPP_HOST: {{ .Release.Name }}-blackduck-webapp.{{ .Release.Namespace }}.svc
  HUB_CFSSL_HOST: {{ .Release.Name }}-blackduck-cfssl
  {{- else }}
  ALERT_HOSTNAME: localhost
  ALERT_SERVER_PORT: "8443"
  {{- if .Values.enableStandalone }}
  HUB_CFSSL_HOST: {{ .Release.Name }}-cfssl
  {{- end }}
  {{- end }}
  {{- if .Values.environs }}
  {{- .Values.environs | toYaml | nindent 2 | trimSuffix "\n" }}
  {{- end }}
metadata:
  labels:
    app: alert
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}-environs
  namespace: {{ .Release.Namespace }}
---
