apiVersion: v1
kind: Secret
data:
  {{- if .Values.setEncryptionSecretData -}}
  {{- include "alert.encryptionSecretEnvirons" . | nindent 2 }}
  {{- end }}
  {{- if .Values.secretEnvirons }}
  {{- range $key, $value := .Values.secretEnvirons }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
metadata:
  labels:
    app: alert
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}-environs-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
---