version: '2.1'
services:
  cfssl:
    image: blackducksoftware/blackduck-cfssl:1.0.0
    volumes: ['cert-volume:/etc/cfssl']
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'http://localhost:8888/api/v1/cfssl/scaninfo']
      interval: 30s
      timeout: 10s
      retries: 5
    user: cfssl:root
    restart: always
    mem_limit: 512M
  alert:
    image: blackducksoftware/blackduck-alert:VERSION_TOKEN
    ports: ['8443:8443']
    links: [cfssl]
    env_file: [blackduck-alert.env]
    user: alert:root
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'https://localhost:8443/alert/api/about']
      interval: 30s
      timeout: 10s
      retries: 5
    volumes: ['alert-db-volume:/opt/blackduck/alert/alert-config/data']
    mem_limit: 2560M
volumes: {cert-volume: null, alert-db-volume: null }
