apiVersion: v1
kind: ConfigMap
data:
  ALERT_HOSTNAME: {{ .Values.alert.hostname | quote }}
  ALERT_SERVER_PORT: {{ .Values.alert.port | quote }}
  ALERT_FORWARD_HEADERS_STRATEGY: {{ .Values.alert.forwardHeadersStrategy | quote }}
  {{- if .Values.deployAlertWithBlackDuck }}
  HUB_WEBAPP_HOST: {{ required "must --set blackDuckName" .Values.blackDuckName }}-blackduck-webapp.{{ required "must --set blackDuckNamespace" .Values.blackDuckNamespace }}.svc
  HUB_CFSSL_HOST: {{ .Values.blackDuckName }}-blackduck-cfssl.{{ .Values.blackDuckNamespace }}.svc
  {{- else }}
  {{- if .Values.enableStandalone }}
  HUB_CFSSL_HOST: {{ .Release.Name }}-cfssl
  {{- end -}}
  {{- end -}}
  {{- if and .Values.exposedNodePort (eq .Values.exposedServiceType "NodePort") }}
  PUBLIC_ALERT_WEBSERVER_PORT: {{ quote .Values.exposedNodePort }}
  {{- end -}}
  {{- if .Values.environs }}
  {{- include "alert.environs" . | nindent 2 }}
  {{- end }}
metadata:
  labels:
    app: alert
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}-environs
  namespace: {{ .Release.Namespace }}
---
