apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert
  namespace: blackduck
spec:
  selector:
    matchLabels:
      app: alert
      tier: alert
  replicas: 1
  template:
    metadata:
      name: alert
      labels:
        app: alert
        tier: alert
    spec:
      volumes:
      - emptyDir: {}
        name: alert-db-volume
      containers:
      - image: blackducksoftware/blackduck-alert:VERSION_TOKEN
        name: alert
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/docker-healthcheck.sh
            - 'https://localhost:8443/alert/api/about'
          initialDelaySeconds: 240
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 5
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /opt/blackduck/alert/alert-config/data
            name: alert-db-volume
        ports:
        - containerPort: 8443
          hostPort: 8443
          protocol: TCP
        resources:
          requests:
            memory: 512M
          limits:
            memory: 512M
        envFrom:
        - configMapRef:
            name: blackduck-alert-config
