version: '3.6'
services:
#  alert:
#    # uncomment environment to set environment variables for the alert service.
#    environment:
#      - ALERT_HOSTNAME=localhost
#      - ALERT_SERVER_PORT=8443
#      - ALERT_LOGGING_LEVEL=INFO
#
#     # uncomment the following line if you are using a reverse proxy or load balancer
#      - ALERT_FORWARD_HEADERS_STRATEGY=native
#
#     # -- Database Settings
#      - ALERT_DB_HOST=alertdb
#      - ALERT_DB_PORT=5432
#      - ALERT_DB_NAME=alertdb
#      - ALERT_DB_SSL_MODE=require
#
#     # -- ALERT RESET VARIABLES
#      - ALERT_LDAP_DISABLED=false
#      - ALERT_SAML_DISABLED=false
#      - ALERT_ADMIN_USER_PASSWORD_RESET=false
#
#
#     # -- Proxy Settings
#      - ALERT_COMPONENT_SETTINGS_SETTINGS_PROXY_HOST=
#      - ALERT_COMPONENT_SETTINGS_SETTINGS_PROXY_PORT=
#      - ALERT_COMPONENT_SETTINGS_SETTINGS_PROXY_USERNAME=
#      - ALERT_COMPONENT_SETTINGS_SETTINGS_PROXY_PASSWORD=
#     # Provider Settings
#     # -- BlackDuck Provider Settings
#      - ALERT_PROVIDER_BLACKDUCK_PROVIDER_COMMON_CONFIG_NAME=Default Config
#      - ALERT_PROVIDER_BLACKDUCK_PROVIDER_COMMON_CONFIG_ENABLED=true
#      - ALERT_PROVIDER_BLACKDUCK_BLACKDUCK_URL=
#      - ALERT_PROVIDER_BLACKDUCK_BLACKDUCK_API_KEY=
#      - ALERT_PROVIDER_BLACKDUCK_BLACKDUCK_TIMEOUT=
#     # Component Settings
#
#     # -- LDAP
#      - ALERT_COMPONENT_AUTHENTICATION_SETTINGS_LDAP_ENABLED=
#      - ALERT_COMPONENT_AUTHENTICATION_SETTINGS_LDAP_SERVER=
#      - ALERT_COMPONENT_AUTHENTICATION_SETTINGS_LDAP_AUTHENTICATION_TYPE=
#      - ALERT_COMPONENT_AUTHENTICATION_SETTINGS_LDAP_GROUP_ROLE_ATTRIBUTE=
#      - ALERT_COMPONENT_AUTHENTICATION_SETTINGS_LDAP_GROUP_SEARCH_BASE=
#      - ALERT_COMPONENT_AUTHENTICATION_SETTINGS_LDAP_GROUP_SEARCH_FILTER=
#      - ALERT_COMPONENT_AUTHENTICATION_SETTINGS_LDAP_MANAGER_DN=
#      - ALERT_COMPONENT_AUTHENTICATION_SETTINGS_LDAP_MANAGER_PASSWORD=
#      - ALERT_COMPONENT_AUTHENTICATION_SETTINGS_LDAP_REFERRAL=
#      - ALERT_COMPONENT_AUTHENTICATION_SETTINGS_LDAP_USER_ATTRIBUTES=
#      - ALERT_COMPONENT_AUTHENTICATION_SETTINGS_LDAP_USER_DN_PATTERNS=
#      - ALERT_COMPONENT_AUTHENTICATION_SETTINGS_LDAP_USER_SEARCH_BASE=
#      - ALERT_COMPONENT_AUTHENTICATION_SETTINGS_LDAP_USER_SEARCH_FILTER=
#     # -- SAML
#      - ALERT_COMPONENT_AUTHENTICATION_SETTINGS_SAML_ENABLED=
#      - ALERT_COMPONENT_AUTHENTICATION_SETTINGS_SAML_ENTITY_BASE_URL=
#      - ALERT_COMPONENT_AUTHENTICATION_SETTINGS_SAML_ENTITY_ID=
#      - ALERT_COMPONENT_AUTHENTICATION_SETTINGS_SAML_FORCE_AUTH=
#      - ALERT_COMPONENT_AUTHENTICATION_SETTINGS_SAML_METADATA_URL=
#      - ALERT_COMPONENT_AUTHENTICATION_SETTINGS_SAML_ROLE_ATTRIBUTE_MAPPING_NAME=
#     # -- User Management
#      - ALERT_COMPONENT_AUTHENTICATION_SETTINGS_ROLE_MAPPING_NAME_ADMIN=
#      - ALERT_COMPONENT_AUTHENTICATION_SETTINGS_ROLE_MAPPING_NAME_JOB_MANAGER=
#      - ALERT_COMPONENT_AUTHENTICATION_SETTINGS_ROLE_MAPPING_NAME_USER=
#      - ALERT_COMPONENT_AUTHENTICATION_SETTINGS_SAML_ROLE_ATTRIBUTE_MAPPING_NAME=
#     # -- Scheduling
#      - ALERT_COMPONENT_SCHEDULING_SCHEDULING_PURGE_DATA_FREQUENCY=
#      - ALERT_COMPONENT_SCHEDULING_SCHEDULING_DAILY_PROCESSOR_HOUR=
#     # Channel settings
#     # -- Jira Cloud Channel Settings
#      - ALERT_CHANNEL_JIRA_CLOUD_JIRA_CLOUD_URL=
#      - ALERT_CHANNEL_JIRA_CLOUD_JIRA_CLOUD_ADMIN_EMAIL_ADDRESS=
#      - ALERT_CHANNEL_JIRA_CLOUD_JIRA_CLOUD_ADMIN_API_TOKEN=
#     # -- Email Channel Settings
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_HOST=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_USER=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_PASSWORD=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_PORT=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_CONNECTION_TIMEOUT=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_TIMEOUT=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_WRITETIMEOUT=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_FROM=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_LOCALHOST=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_LOCALADDRESS=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_LOCALPORT=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_EHLO=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_AUTH=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_AUTH_MECHANISMS=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_AUTH_LOGIN_DISABLE=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_AUTH_PLAIN_DISABLE=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_AUTH_DIGEST_MD5_DISABLE=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_AUTH_NTLM_DISABLE=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_AUTH_NTLM_DOMAIN=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_AUTH_NTLM_FLAGS=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_AUTH_XOAUTH2_DISABLE=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_SUBMITTER=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_DSN_NOTIFY=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_DNS_RET=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_ALLOW_8_BITMIME=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_SEND_PARTIAL=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_SASL_ENABLE=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_SASL_MECHANISMS=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_SASL_AUTHORIZATIONID=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_SASL_REALM=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_SASL_USECANONICALHOSTNAME=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_QUITWAIT=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_REPORTSUCCESS=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_SSL_ENABLE=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_SSL_CHECKSERVERIDENTITY=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_SSL_TRUST=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_SSL_PROTOCOLS=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_SSL_CIPHERSUITES=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_STARTTLS_ENABLE=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_STARTTLS_REQUIRED=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_PROXY_HOST=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_PROXY_PORT=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_SOCKS_HOST=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_SOCKS_PORT=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_MAILEXTENSION=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_USERSET=
#      - ALERT_CHANNEL_EMAIL_MAIL_SMTP_NOOP_STRICT=
#    # uncomment the secrets section to use secrets.
#    # Please uncomment the secrets in use; both the required and the optional secrets.
#    # Note: choose one jssecacerts or cacerts secret not both.
#    secrets:
#      - ALERT_ENCRYPTION_PASSWORD
#      - ALERT_ENCRYPTION_GLOBAL_SALT
#      - WEBSERVER_CUSTOM_CERT_FILE
#      - WEBSERVER_CUSTOM_KEY_FILE
#      - ALERT_DB_USERNAME
#      - ALERT_DB_PASSWORD
#      - ALERT_DB_ADMIN_USERNAME
#      - ALERT_DB_ADMIN_PASSWORD
#      - ALERT_DB_SSL_KEY_PATH
#      - ALERT_DB_SSL_CERT_PATH
#      - ALERT_DB_SSL_ROOT_CERT_PATH
#      # -- Custom Certificate Usage
#      - source: jssecacerts
#        target: jssecacerts
#        mode: 0664
#      - source: cacerts
#        target: cacerts
#        mode: 0664
#      - ALERT_TRUST_STORE_PASSWORD
#
# uncomment the secrets in use; both the required and the optional secrets.
#secrets:
#  ALERT_ENCRYPTION_PASSWORD:
#    external: true
#    name: "<STACK_NAME>_ALERT_ENCRYPTION_PASSWORD"
#  ALERT_ENCRYPTION_GLOBAL_SALT:
#    external: true
#    name: "<STACK_NAME>_ALERT_ENCRYPTION_GLOBAL_SALT"
#  WEBSERVER_CUSTOM_CERT_FILE:
#    external: true
#    name: "<STACK_NAME>_WEBSERVER_CUSTOM_CERT_FILE"
#  WEBSERVER_CUSTOM_KEY_FILE:
#    external: true
#    name: "<STACK_NAME>_WEBSERVER_CUSTOM_KEY_FILE"
#  jssecacerts:
#    external: true
#    name: "<STACK_NAME>_jssecacerts"
#  cacerts:
#    external: true
#    name: "<STACK_NAME>_cacerts"
#  ALERT_TRUST_STORE_PASSWORD:
#    external: true
#    name: "<STACK_NAME>_ALERT_TRUST_STORE_PASSWORD"
#  ALERT_DB_USERNAME:
#    external: true
#    name: "<STACK_NAME>_ALERT_DB_USERNAME"
#  ALERT_DB_PASSWORD:
#    external: true
#    name: "<STACK_NAME>_ALERT_DB_PASSWORD"
#  ALERT_DB_ADMIN_USERNAME:
#    external: true
#    name: "<STACK_NAME>_ALERT_DB_ADMIN_USERNAME"
#  ALERT_DB_ADMIN_PASSWORD:
#    external: true
#    name: "<STACK_NAME>_ALERT_DB_ADMIN_PASSWORD"
#  ALERT_DB_SSL_KEY_PATH:
#    external: true
#    name: "<STACK_NAME>_ALERT_DB_SSL_KEY_PATH"
#  ALERT_DB_SSL_CERT_PATH:
#    external: true
#    name: "<STACK_NAME>_ALERT_DB_SSL_CERT_PATH"
#  ALERT_DB_SSL_ROOT_CERT_PATH:
#    external: true
#    name: "<STACK_NAME>_ALERT_DB_SSL_ROOT_CERT_PATH"
