---
apiVersion: v1
data:
  {{- include "enablePostgresSSL" . | nindent 2 }}
  {{- if not .Values.postgres.isExternal }}
  ALERT_DB_HOST: {{ .Release.Name }}-postgres
  {{- else }}
  ALERT_DB_HOST: {{ required "must provide --set postgres.host=\"\"" .Values.postgres.host }}
  {{- end }}
  ALERT_DB_PORT: {{ .Values.postgres.port | quote }}
  {{- if not .Values.postgres.dbCredential.secretName }}
  ALERT_DB_USERNAME: {{ .Values.postgres.userUserName }}
  {{- end }}
  ALERT_DB_NAME: {{ .Values.postgres.databaseName }}
  {{- if not .Values.postgres.dbAdminCredential.secretName }}
  ALERT_DB_ADMIN_USERNAME: {{ .Values.postgres.adminUserName }}
  {{- end }}
kind: ConfigMap
metadata:
  labels:
    app: alert
    component: postgres
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}-db-config
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
data:
  ALERT_POSTGRES_USER_PASSWORD_FILE: {{ .Values.postgres.userPassword | b64enc }}
  {{- if .Values.postgres.adminPassword }}
  ALERT_POSTGRES_ADMIN_PASSWORD_FILE: {{ .Values.postgres.adminPassword | b64enc }}
  {{- else }}
  ALERT_POSTGRES_ADMIN_PASSWORD_FILE: {{ .Values.postgres.userPassword | b64enc }}
  {{- end }}
kind: Secret
metadata:
  labels:
    app: alert
    component: postgres
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}-db-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
