version: '3.6'
services:
  alertdb:
    image: blackducksoftware/blackduck-alert-db:ALERT_VERSION_TOKEN
    ports: ['5432']
    hostname: alertdb
    volumes: ['alert-db-postgres-volume:/var/lib/postgresql/data']
    healthcheck:
      test: [ CMD, /usr/local/bin/alertdb-healthcheck.sh ]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      mode: replicated
      restart_policy: { condition: on-failure, delay: 5s, window: 60s }
      resources:
        limits: { memory: 1024M }
        reservations: { memory: 1024M }
  alert-rabbitmq:
    image: blackducksoftware/blackduck-alert-rabbitmq:ALERT_VERSION_TOKEN
    hostname: alert-rabbitmq
    healthcheck:
      test: [ CMD, rabbitmq-diagnostics, -q, status ]
      interval: 30s
      timeout: 60s
      retries: 15
      start_period: 7200s
    volumes: [ 'alert-rabbitmq-volume:/opt/blackduck/rabbitmq/logs' ]
    deploy:
      mode: replicated
      restart_policy: { condition: on-failure, delay: 15s, window: 60s }
      resources:
        limits: { memory: 1024M }
        reservations: { memory: 1024M }
  alert:
    image: blackducksoftware/blackduck-alert:ALERT_VERSION_TOKEN
    ports: [ '8443:8443' ]
    env_file: [ blackduck-alert.env ]
    healthcheck:
      test: [ CMD, /usr/local/bin/docker-healthcheck.sh, 'https://localhost:8443/alert/api/about',
              /opt/blackduck/alert/security/root.crt, /opt/blackduck/alert/security/blackduck_system.crt,
              /opt/blackduck/alert/security/blackduck_system.key ]
      interval: 30s
      timeout: 60s
      retries: 15
      start_period: 7200s
    volumes: ['alert-db-volume:/opt/blackduck/alert/alert-config/data']
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 15s, window: 60s}
      resources:
        limits: {memory: 2560M}
        reservations: {memory: 2560M}
volumes: {alert-db-volume: null, alert-db-postgres-volume: null}
