// Global Config
export const CONFIG_FETCHING = 'CONFIG_FETCHING';
export const CONFIG_FETCHED = 'CONFIG_FETCHED';
export const CONFIG_UPDATING = 'CONFIG_UPDATING';
export const CONFIG_UPDATED = 'CONFIG_UPDATED';
export const CONFIG_TESTING = 'CONFIG_TESTING';
export const CONFIG_TEST_SUCCESS = 'CONFIG_TEST_SUCCESS';
export const CONFIG_TEST_FAILED = 'CONFIG_TEST_FAILED';

// Email Config Actions
export const EMAIL_CONFIG_FETCHING = 'EMAIL_CONFIG_FETCHING';
export const EMAIL_CONFIG_FETCHED = 'EMAIL_CONFIG_FETCHED';
export const EMAIL_CONFIG_UPDATING = 'EMAIL_CONFIG_UPDATING';
export const EMAIL_CONFIG_UPDATED = 'EMAIL_CONFIG_UPDATED';
export const EMAIL_CONFIG_SHOW_ADVANCED = 'EMAIL_CONFIG_SHOW_ADVANCED';
export const EMAIL_CONFIG_HIDE_ADVANCED = 'EMAIL_CONFIG_HIDE_ADVANCED';

// Auth related Actions
export const SESSION_LOGGING_IN = 'SESSION_LOGGING_IN';
export const SESSION_LOGGED_IN = 'SESSION_LOGGED_IN';
export const SESSION_LOGGED_OUT = 'SESSION_LOGGED_OUT';
export const SESSION_LOGIN_ERROR = 'SESSION_LOGIN_ERROR';
export const SESSION_SHOW_ADVANCED = 'SESSION_SHOW_ADVANCED';
export const SESSION_HIDE_ADVANCED = 'SESSION_HIDE_ADVANCED';
export const SERIALIZE = 'SERIALIZE';
